---
meta:
  size: default
  instances: 3
  default:
    azs: [z1,z2]
  username: (( vault $CREDENTIALS "/rabbitmq/system:username" ))
  password: (( vault $CREDENTIALS "/rabbitmq/system:password" ))

releases:
  - { name: rabbitmq-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: node
    instances: (( grab meta.instances ))
    azs: (( grab meta.azs || meta.default.azs ))
    networks: [name: (( grab meta.net || 'rabbitmq-service' ))]
    stemcell: default

    vm_type: (( grab meta.size ))

    jobs:
      - name:    rabbitmq
        release: rabbitmq-forge
        properties:
          default_user:     (( grab meta.username ))
          default_password: (( grab meta.password ))
        provides:
          rabbitmq-servers: { as: rabbitmq-servers,   ip_addresses: true }
        consumes:
          rabbitmq-servers: { from: rabbitmq-servers, ip_addresses: true }
